import type { EnemyKind } from './model.ts';

export const BARK_RULES = Object.freeze({ chance: .25, maxVisible: 3, duration: 2.8, fadeIn: .12, fadeOut: .25, spacing: .8, admissionWindow: 4, disengagedFor: 30, retryAfter: 45, maxTracked: 64 });

/** Authored short encounter lines. Creatures without language deliberately have no pool. */
export const BATTLE_BARKS = Object.freeze({
  goblin: Object.freeze([
    "Die! Leave the boots!",
    "Your boots! My size!",
    "Your plan was to win?",
    "Shiny sword. Mine now!",
    "Stop moving, pockets!",
    "I'll bite your kneecaps!",
    "Big pockets. Bad odds.",
    "Fear me! A little!",
    "That's my stabbing face!",
    "You drop good things?",
    "Chief said no witnesses!",
    "Nobody step on my loot!",
    "Your purse looks heavy!",
    "I dibs the shiny bits!",
    "Come back, walking loot!",
    "This knife was a spoon!",
    "You look easy. Probably!",
    "I'll sell your hat!",
    "Small goblin! Big plans!",
    "Pay the goblin tax!",
  ]),
  goblinChief: Object.freeze([
    "Charge! I'll supervise!",
    "Leave the shiny bits!",
    "Surround! Not each other!",
    "My horn means trouble!",
    "Kneel! I'm taller then!",
    "I get first pick!",
    "Form a scary shape!",
    "Stop counting! Attack!",
    "Get them! Keep my banner!",
    "I planned this ambush!",
    "No fleeing before me!",
    "Less squealing! More steel!",
    "Behold my best minions!",
    "Nobody steal my victory!",
    "Your skull gets a flag!",
    "Forward, expendables!",
    "That's an order! I think!",
    "I'll gut you personally!",
    "Bring me their fancy hat!",
    "Chief gets the big half!",
  ]),
  stalker: Object.freeze([
    "I smell a pulse. Rude.",
    "Your shadow told me.",
    "Still breathing? Greedy.",
    "A fresh grave walks.",
    "Let me borrow your warmth.",
    "Don't look behind you.",
    "The dirt misses you.",
    "I was having a nice rot.",
    "Hush. Your bones rattle.",
    "Such noisy lungs.",
    "Your pulse gives you away.",
    "I'll keep your shadow.",
    "You smell unfinished.",
    "Your grave is ready.",
    "All paths end below.",
    "I know a quiet place.",
    "I've been dying to meet you.",
    "These claws need work.",
    "Keep running. I don't tire.",
    "So much fuss over dying.",
  ]),
  brute: Object.freeze([
    "Hold still. Heavy hammer.",
    "You. Ground. Now.",
    "I'll bury you standing.",
    "Hammer says no.",
    "Too tall. I'll fix it.",
    "One swing. Less talking.",
    "Armor makes nice noise.",
    "I brought the big answer.",
    "Small grave. You'll fit.",
    "Bones break. Mine know.",
    "Stop dodging my point.",
    "You woke the wrong grave.",
    "I flatten problems.",
    "Dirt needs feeding.",
    "Shield won't help much.",
    "I'll knock twice.",
    "This hammer digs too.",
    "Quiet comes after smash.",
    "I hate quick ones.",
    "Lie down. Save time.",
  ]),
  caster: Object.freeze([
    "May your socks stay wet!",
    "A curse upon your knees!",
    "You'll make excellent mulch.",
    "Hold still, ingredient!",
    "I've hexed nicer people.",
    "The bog wants a word.",
    "Your aura smells cheap.",
    "I'll curdle your courage!",
    "Mind the curse. It's fresh.",
    "Your doom needs stirring.",
    "May every boot leak!",
    "I curse you with elbows!",
    "Oh, good. Fresh mistakes.",
    "Don't bleed in my herbs.",
    "Your bones are overdue.",
    "A pinch of you will do.",
    "I'll sour your luck!",
    "Kneel before the mildew!",
    "You're interrupting a hex.",
    "May your soup grow teeth!",
  ]),
  archer: Object.freeze([
    "Run. I enjoy the practice.",
    "I only need one opening.",
    "Keep the hat. Helps me aim.",
    "You're in my good range.",
    "That tree won't save you.",
    "One arrow. No applause.",
    "Try a less obvious dodge.",
    "I'll pin that thought.",
    "Your armor has gaps.",
    "Stand proud. It's easier.",
    "Wind's right. You're wrong.",
    "I've shot smaller egos.",
    "No charge for the arrow.",
    "You rustle like a cart.",
    "I'll need that arrow back.",
    "Your next step is mine.",
    "The thorns warned you.",
    "Nice cloak. Hold it still.",
    "Another walking target.",
    "Stay there. Briefly.",
  ]),
  warden: Object.freeze([
    "Visiting hours are over.",
    "None disturb my vigil.",
    "Your grave awaits below.",
    "Kneel before the stillness.",
    "The dead require silence.",
    "You tread on borrowed time.",
    "I have kept worse things out.",
    "This tomb has no vacancies.",
    "Leave your breath at the door.",
    "Even kings wait outside.",
    "Your epitaph will be brief.",
    "I shall file you under dust.",
    "No loitering among the dead.",
    "My patience outlived empires.",
    "I did not invite the living.",
    "Trespass ends here.",
    "The stones know your weight.",
    "You are early for burial.",
    "Do not scuff the tombstones.",
    "Your final audience begins.",
  ]),
});
export type BarkKind = keyof typeof BATTLE_BARKS;
export function canBark(kind: EnemyKind): kind is BarkKind { return Object.hasOwn(BATTLE_BARKS, kind); }
