import type { CharacterSheet, EquipmentSlot, Item, ItemKind, SkillId, StatKey } from './character-types.ts';
import type { ItemMaterialId } from './item-materials.ts';

export const UNIQUE_COLOR = '#ef82ad';
export const UNIQUE_EDGE = '#ba8bf1';
export const UNIQUE_SYMBOL = '✧';
export const UNIQUE_RULES = Object.freeze({ storedCasts: 3, emberLifetime: 20, shieldSpeed: 380, shieldRange: 220,
  wardRadius: 140, wardSpellCap: 3, novaRange: 420, decoyDuration: 2, decoyLife: .2, returnWindow: 2, fissureRange: 350, fissureSpeed: 310, shatterDelay: .6, shatterRadius: 70, borrowedLife: .2, borrowedDuration: 4,
  drawTime:.6, drawDamage:2, drawReach:1.3, rainTravel:240, pursuitTime:.3, pursuitRadius:28,
  bastionCap:2, bastionWindow:6, harvestWindow:4, conductorWindow:3 });
export interface UniqueDefinition {
  readonly id: string; readonly name: string; readonly kind: ItemKind; readonly profile?: string;
  readonly material: ItemMaterialId; readonly skill: SkillId; readonly power: string;
  readonly details: string;
  readonly affixes: readonly StatKey[];
}
export const UNIQUES: readonly UniqueDefinition[] = Object.freeze([
  {id:'dervish-grasp',name:'Dervish’s Grasp',kind:'gloves',material:'leather',skill:'whirlwind',
    power:'Hold Whirlwind to spin at full movement speed.',
    details:'Hold Whirlwind to spin while moving at full speed. Each revolution deals its normal damage and costs its normal mana.',
    affixes:['attackSpeedPercent','damagePercent','areaPercent','maxHp']},
  {id:'returning-verdict',name:'Returning Verdict',kind:'shield',profile:'iron-buckler',material:'iron',skill:'shieldBash',
    power:'Shield Bash throws your shield outward and back.',
    details:'Shield Bash throws your shield outward and back. Each enemy can be struck and stunned once on each journey.',
    affixes:['damagePercent','blockChance','armor','areaPercent']},
  {id:'homeward-thorn',name:'Homeward Thorn',kind:'weapon',profile:'crescent-recurve',material:'ashwood',skill:'volley',
    power:'Thorn Volley arrows return to their firing position.',
    details:'Thorn Volley arrows return to their firing position. Each journey has its own hits and piercing allowance.',
    affixes:['damagePercent','attackSpeedPercent','critChance','critDamage']},
  {id:'cinderheart-testament',name:'Cinderheart Testament',kind:'grimoire',profile:'ember-codex',material:'leather',skill:'fireball',
    power:'Store up to 3 Fireballs for 20s. Your next basic attack releases them.',
    details:'Fireball stores up to 3 paid casts for 20 seconds. Each cast keeps its own expiry. Your next basic attack releases every stored fireball toward your aim.',
    affixes:['spellDamagePercent','intelligence','maxHp','spellweavePercent']},
  {id:'winters-reach',name:'Winter’s Reach',kind:'orb',profile:'rime-orb',material:'glass',skill:'iceNova',
    power:'Cast Ice Nova at your aim.',
    details:'Ice Nova erupts at your aim, up to 420 reach. Echoing Frost repeats at the same position. Solid terrain blocks targeting.',
    affixes:['spellDamagePercent','areaPercent','castSpeedPercent','maxHp']},
  {id:'broken-seal',name:'The Broken Seal',kind:'grimoire',profile:'astral-grimoire',material:'leather',skill:'runicWard',
    power:'When damage breaks your ward, it explodes.',
    details:'When enemy damage breaks Runic Ward, release an arcane explosion equal to damage absorbed, capped at 300% weapon spell damage. Expiration does not trigger it.',
    affixes:['spellDamagePercent','maxHp','armor','intelligence']},
  {id:'ashen-double',name:'Ashen Double',kind:'cloak',material:'cloth',skill:'smokeVeil',
    power:'Smoke Veil leaves a fragile double for 2s.',
    details:'Smoke Veil leaves a fragile double for 2 seconds. Nearby ordinary enemies may attack it; already committed attacks, elites and bosses are not redirected.',
    affixes:['dexterity','maxHp','armor','critChance']},
  {id:'duelists-return',name:'Duelist’s Return',kind:'boots',material:'leather',skill:'lunge',
    power:'After Lunge, reactivate within 2s to return for free.',
    details:'After Lunge, reactivate within 2 seconds to dash back toward your starting position. Returning costs no mana, deals no damage and does not reset the cooldown.',
    affixes:['moveSpeedPercent','damagePercent','maxHp','armor']},
  {id:'gravetide',name:'Gravetide',kind:'weapon',profile:'grave-maul',material:'iron',skill:'earthshatter',
    power:'Earthshatter sends a traveling fissure.',
    details:'Earthshatter sends a traveling fissure along your aim. It carries the full damage and stun through each enemy once, stopping at solid terrain.',
    affixes:['damagePercent','strength','areaPercent','critDamage']},
  {id:'pale-huntsman',name:'Pale Huntsman’s Signet',kind:'ring',profile:'garnet-band',material:'silver',skill:'ghostHunt',
    power:'Your spectral archer fires Ghost Hunt’s echoes.',
    details:'Ghost Hunt leaves a spectral archer at your casting position. Your arrow actions trigger its finite echoes toward your aim while you reposition.',
    affixes:['damagePercent','dexterity','critChance','maxHp']},
  {id:'rimeheart-spire',name:'Rimeheart Spire',kind:'weapon',profile:'hoarfrost-wand',material:'ashwood',skill:'frostLance',
    power:'Frost Lance shatters after 0.6s.',
    details:'Frost Lances lodge at their final contact and shatter after 0.6 seconds, dealing their full damage and slow in a small area. Piercing hits remain intact.',
    affixes:['spellDamagePercent','castSpeedPercent','intelligence','areaPercent']},
  {id:'borrowed-life',name:'Vessel of Borrowed Life',kind:'amulet',profile:'warden-amulet',material:'silver',skill:'siphon',
    power:'Unused Siphon healing becomes a barrier for 4s.',
    details:'Unused Soul Siphon healing becomes a barrier for 4 seconds, up to 20% maximum life. It shares capacity with Runic Ward and cannot trigger The Broken Seal.',
    affixes:['maxHp','spellDamagePercent','intelligence','armor']},
  {id:'heartwood-draw',name:'Heartwood Draw',kind:'weapon',profile:'warden-longbow',material:'ashwood',skill:'piercingShot',
    power:'Hold Piercing Shot for 0.6s: double damage and 30% more reach.',
    details:'Hold Piercing Shot to charge its damage and reach. After 0.6 seconds it deals double damage with 30% more reach. Release to fire; quick releases retain normal damage and mana cost.',
    affixes:['damagePercent','critDamage','manaCostPercent','strength']},
  {id:'briarfall-mantle',name:'Briarfall Mantle',kind:'cloak',material:'cloth',skill:'rainOfArrows',
    power:'Rain of Arrows advances along your aim.',
    details:'Rain of Arrows advances 240 units from its target along your firing direction, carrying its normal waves and damage. Solid terrain stops the curtain.',
    affixes:['damagePercent','areaPercent','manaRegen','maxHp']},
  {id:'thread-of-pursuit',name:'Thread of Pursuit',kind:'amulet',profile:'hawk-talisman',material:'silver',skill:'ricochet',
    power:'Unused Ricochet rebounds can strike previous targets again.',
    details:'When no fresh target remains, Ricochet spends its remaining rebounds looping back into previously struck enemies. Each loop takes 0.3 seconds; repeated contacts cannot restore life.',
    affixes:['damagePercent','critChance','manaCostPercent','maxMana']},
  {id:'patient-bastion',name:'The Patient Bastion',kind:'shield',profile:'bastion-tower',material:'iron',skill:'bulwark',
    power:'Move freely during Bulwark. Blocked damage empowers your next basic melee attack.',
    details:'Move at full speed while raising Bulwark. Its blocked damage charges your next basic melee attack for 6 seconds, adding up to 200% of its weapon damage. The charge is consumed once per attack.',
    affixes:['armor','blockChance','damagePercent','maxHp']},
  {id:'red-harvest',name:'Red Harvest',kind:'weapon',profile:'rondel-dagger',material:'steel',skill:'backstab',
    power:'Rear Backstab marks the target for 4s. Your next Backstab counts as a rear strike.',
    details:'A rear Backstab marks its victim for 4 seconds. Your next Backstab against that enemy counts as a rear strike from any direction and consumes the mark. That follow-up cannot renew it.',
    affixes:['damagePercent','critDamage','attackSpeedPercent','lifeOnHit']},
  {id:'stormglass-reliquary',name:'Stormglass Reliquary',kind:'orb',profile:'astral-orb',material:'glass',skill:'arcLightning',
    power:'Arc Lightning starts at a conductor placed at your aim.',
    details:'Arc Lightning starts from a conductor placed at your aim within weapon reach and line of sight. Each cast moves the conductor; it lasts 3 seconds and never attacks on its own.',
    affixes:['spellDamagePercent','castSpeedPercent','manaRegen','maxHp']},
  {id:"horizon-edge",name:"Horizon’s Edge",kind:"gloves",material:"steel",skill:"cleave",
    power:"Crescent Cleave becomes a piercing traveling crescent.",
    details:"Crescent Cleave sends a crescent 280 units along your aim instead of sweeping around you. It carries full weapon damage and hits each enemy once; reach Techniques widen it. Terrain stops it.",
    affixes:["damagePercent","attackSpeedPercent","critDamage","strength"]},
  {id:"undertow-grasp",name:"Undertow Grasp",kind:"gloves",material:"iron",skill:"repulse",
    power:"Repulse pulls ordinary enemies toward you before stunning them.",
    details:"Repulse draws ordinary enemies up to 70 units toward you, then deals its normal damage and stun. It cannot pull elites, champions or bosses, or pull through walls.",
    affixes:["damagePercent","armor","maxHp","cooldownPercent"]},
  {id:"oathplate",name:"Oathplate",kind:"chest",material:"steel",skill:"brace",
    power:"Brace trades mitigation for a life-scaled barrier.",
    details:"Brace replaces its damage reduction with a barrier equal to its mitigation percentage of maximum life, capped at 35%. It lasts for Brace’s duration and never stacks with itself.",
    affixes:["armor","maxHp","vitality","cooldownPercent"]},
  {id:"war-drummers-crown",name:"War Drummer’s Crown",kind:"head",material:"iron",skill:"rallyOfIron",
    power:"Rally of Iron empowers every melee action for half its duration.",
    details:"Rally of Iron has no charge limit, but lasts half as long. Each melee action gains the normal Rally bonus; its defensive reduction remains.",
    affixes:["damagePercent","attackSpeedPercent","maxHp","strength"]},
  {id:"foundation-of-kings",name:"Foundation of Kings",kind:"legs",material:"steel",skill:"ironCitadel",
    power:"Iron Citadel becomes a fortress you can return to.",
    details:"Iron Citadel’s protection lasts twice as long but only applies inside its original impact circle. Leaving suspends protection; returning restores it until it expires. The opening strike is unchanged.",
    affixes:["armor","maxHp","areaPercent","vitality"]},
  {id:"frostwake-soles",name:"Frostwake Soles",kind:"boots",material:"leather",skill:"sidestep",
    power:"Sidestep leaves a freezing snare at your departure.",
    details:"Sidestep leaves a 65-unit frost patch for 3 seconds, slowing enemies by 45%. It deals no damage and grants no invulnerability. Bosses retain their normal control resistance.",
    affixes:["moveSpeedPercent","dexterity","maxHp","cooldownPercent"]},
  {id:"skystrider-greaves",name:"Skystrider Greaves",kind:"legs",material:"leather",skill:"vaultingShot",
    power:"Vaulting Shot advances and fires three piercing arrows.",
    details:"Vaulting Shot moves forward instead of backward and fires a three-arrow fan. Each arrow keeps the skill’s damage and piercing. Ghost Hunt echoes only the central arrow.",
    affixes:["damagePercent","dexterity","critChance","maxHp"]},
  {id:"reapers-veil",name:"Reaper’s Veil",kind:"head",material:"cloth",skill:"nightReaping",
    power:"Night Reaping treats controlled enemies as rear targets.",
    details:"Night Reaping prioritizes the lowest-life enemies. Slowed, staggered or stunned targets receive its rear-strike bonus even from the front. The normal target limit still applies.",
    affixes:["damagePercent","critDamage","dexterity","maxHp"]},
  {id:"second-sun",name:"Second Sun",kind:"head",material:"cloth",skill:"meteor",
    power:"Meteor repeats every impact after 0.65 seconds.",
    details:"Every Meteor impact is followed by a second full-damage impact at the same location after 0.65 seconds. Shattered Sky repeats each fragment. Burning ground refreshes without stacking.",
    affixes:["spellDamagePercent","areaPercent","intelligence","maxMana"]},
  {id:"faultline-regalia",name:"Faultline Regalia",kind:"chest",material:"cloth",skill:"cataclysm",
    power:"Cataclysm tears a line of impacts toward your aim.",
    details:"Cataclysm arranges its normal impacts in a line from you toward your aimed destination, instead of a scattered circle. Every impact retains its damage, delay sequence and burning ground. Terrain limits the line.",
    affixes:["spellDamagePercent","areaPercent","maxHp","intelligence"]},
  {id:"stormwalkers-mantle",name:"Stormwalker’s Mantle",kind:"cloak",material:"cloth",skill:"tempest",
    power:"Tempest advances from your casting position.",
    details:"Tempest travels 300 units along your aim over its lifetime instead of following you. Its damage, duration and mana upkeep remain unchanged. Walls stop its advance.",
    affixes:["spellDamagePercent","castSpeedPercent","manaCostPercent","maxHp"]},
  {id:"winter-prison",name:"Winter Prison",kind:"orb",profile:"rime-orb",material:"glass",skill:"absoluteZero",
    power:"Absolute Zero leaves a lingering prison of frost.",
    details:"After its normal damaging waves, Absolute Zero leaves a 6-second field that slows enemies by 75%. The lingering field deals no damage and does not repeatedly freeze.",
    affixes:["spellDamagePercent","areaPercent","maxHp","intelligence"]},
  {id:"roots-of-the-world",name:"Roots of the World",kind:"boots",material:"iron",skill:"ironroot",
    power:"Ironroot also protects against elements while rooted.",
    details:"After standing still for 1.2 seconds, Ironroot’s physical hit reduction also applies to elemental hits. Moving ends this extra protection immediately; armor remains active.",
    affixes:["armor","maxHp","vitality","lifeRegen"]},
  {id:"unbroken-vow",name:"Unbroken Vow",kind:"amulet",profile:"warden-amulet",material:"silver",skill:"bloodOath",
    power:"Blood Oath carries its stacks between enemies.",
    details:"Blood Oath stacks survive changing targets and a target’s death. Melee hits refresh the normal 3-second window. Stacks still expire when you stop attacking.",
    affixes:["damagePercent","attackSpeedPercent","maxHp","lifeOnHit"]},
  {id:"farflight-circlet",name:"Farflight Circlet",kind:"head",material:"leather",skill:"hawkeye",
    power:"Hawkeye arrows pierce one additional enemy.",
    details:"While Hawkeye is active, arrows gain one extra piercing contact. This also applies to active bow skills; it does not create new arrows or free casts.",
    affixes:["damagePercent","critChance","dexterity","projectilePierce"]},
  {id:"briarkeepers-wrap",name:"Briarkeeper’s Wrap",kind:"legs",material:"leather",skill:"thornbound",
    power:"Thornbound clings to enemies after they leave your aura.",
    details:"Thornbound’s slow lingers for 3 seconds after its last pulse, allowing you to kite enemies out of the aura. Bosses still receive half slow potency.",
    affixes:["armor","maxHp","dexterity","moveSpeedPercent"]},
  {id:"prismatic-heart",name:"Prismatic Heart",kind:"amulet",profile:"sage-pendant",material:"silver",skill:"elementalResonance",
    power:"Elemental Resonance exposes every element at once.",
    details:"A direct elemental hit exposes Fire, Frost, Lightning and Arcane together at the aura’s normal strength. Exposures refresh without stacking; the triggering hit only benefits from exposure already present.",
    affixes:["spellDamagePercent","maxHp","intelligence","manaCostPercent"]},
  {id:"stillwater-treads",name:"Stillwater Treads",kind:"boots",material:"cloth",skill:"stillwater",
    power:"Stillwater’s focus fades gradually while moving.",
    details:"Moving drains fully built Stillwater focus over 2 seconds instead of clearing it instantly. Standing still rebuilds focus at the normal rate. No extra mana is generated.",
    affixes:["manaCostPercent","maxMana","moveSpeedPercent","maxHp"]},
  {id:"triune-carapace",name:"Triune Carapace",kind:"chest",material:"iron",skill:"elementalSpikes",
    power:"Elemental Spikes erupts with all three elements together.",
    details:"Elemental Spikes pulses every 1.2 seconds, dealing its normal damage once each as Fire, Frost and Lightning within 90 units. It still needs an equipped melee weapon and reserves the normal mana.",
    affixes:["damagePercent","armor","maxHp","strength"]},
].map(def => Object.freeze({...def,affixes:Object.freeze(def.affixes)})) as UniqueDefinition[]);
export function uniqueSlot(definition:UniqueDefinition):EquipmentSlot {
  const kind=definition.kind;return kind==='ring'?'ring1':['shield','grimoire','orb'].includes(kind)?'offhand':kind as EquipmentSlot;
}
export function uniqueDefinition(item: Pick<Item,'recipe'>): UniqueDefinition | undefined { return UNIQUES.find(u=>u.id===item.recipe.uniqueId); }
export function hasUnique(sheet: CharacterSheet, id: string): boolean {
  return Object.values(sheet.equipped).some(item=>item?.tier==='unique'&&item.recipe.uniqueId===id);
}
/** Preserve Legendary probability exactly; take the equal Unique share proportionally from lower tiers. */
export function withUniqueChance(weights: Readonly<Partial<Record<Item['tier'],number>>>): Record<Item['tier'],number> {
  const result={common:0,magic:0,rare:0,epic:0,legendary:0,unique:0,...weights};
  if(result.unique>0)return result;
  const other=result.common+result.magic+result.rare+result.epic;
  const unique=Math.min(other,result.legendary), factor=other?(other-unique)/other:1;
  for(const key of ['common','magic','rare','epic'] as const)result[key]*=factor;
  result.unique=unique;return result;
}
