import { toolPage, boundedNumber, downloadJSON, reportRoute } from './common.ts';
import { SkillStudy, studyWeapons, type SkillStudyOptions } from './skill-scene.ts';
import { SKILL_DEFINITIONS, skillRequirementLabel, skillIconSVG } from '../skill-content.ts';
import { SKILL_SPECIALIZATIONS } from '../skill-progression.ts';
import { ENEMY_DEFINITIONS } from '../combat-content.ts';
import { World } from '../world.ts';
import { Renderer } from '../renderer.ts';
import { PostFX } from '../postfx.ts';
import { escapeUI as e } from '../ui-components.ts';
import type { SkillId } from '../character-types.ts';
import type { EnemyKind } from '../model.ts';
const root=await toolPage('Skill playground','Every active skill and specialization, executed by the real combat system. Training targets stay still. This isolated study uses a large mana pool and never touches a saved run.');
const q=new URLSearchParams(location.search),skills=Object.values(SKILL_DEFINITIONS);
let id:SkillId=skills.find(s=>s.id===q.get('skill'))?.id??'fireball';
root.insertAdjacentHTML('beforeend',`<div class="skill-workshop"><aside class="tool-panel"><label>Find a skill<input type="search" id="search" placeholder="Name, school, weapon…" style="width:100%;margin:10px 0"></label><div class="tool-list" id="skills"></div></aside><section><form class="tool-toolbar"><label>Weapon<select name="weapon"></select></label><label>Rank<select name="rank">${[1,2,3,4,5,6,7].map(n=>`<option>${n}</option>`).join('')}</select></label><label>Specialization<select name="specialization"></select></label><label>Facing<select name="facing">${['East','Southeast','South','Southwest','West','Northwest','North','Northeast'].map((name,i)=>`<option value="${i}">${name}</option>`).join('')}</select></label><label>Targets<select name="targets"><option value="fan">Frontal cluster</option><option value="line">Piercing line</option><option value="ring">Surrounding ring</option><option value="none">No targets</option></select></label><label>Creature<select name="enemy">${Object.entries(ENEMY_DEFINITIONS).map(([key,d])=>`<option value="${key}">${e(d.name)}</option>`).join('')}</select></label></form><div class="tool-panel"><div id="skill-title"></div><p id="costs"></p><canvas id="arena" width="1200" height="800" aria-label="Skill animation playground"></canvas><div class="tool-toolbar"><button id="play">Play skill</button><button id="pause" disabled>Pause</button><button id="step">Step 1 frame</button><button id="reset">Reset</button><label>Playback<select id="speed"><option value=".25">¼ speed</option><option value=".5">½ speed</option><option value="1" selected>Normal</option><option value="2">2× speed</option></select></label><label style="display:flex;align-items:center"><input id="loop" style="width:auto" type="checkbox">Loop</label><button id="png">Capture PNG</button></div><p class="tool-status" role="status"></p><progress id="timeline" value="0" max="12" style="width:100%" aria-label="Study playback time"></progress><details><summary>Resolved recipe & observed events</summary><button id="export">Export study JSON</button><pre id="recipe"></pre><pre id="events"></pre></details></div></section></div>`);
const form=root.querySelector('form')!,field=(name:string)=>form.elements.namedItem(name) as HTMLSelectElement;
const canvas=root.querySelector<HTMLCanvasElement>('#arena')!,renderer=new Renderer(),fx=new PostFX(canvas),world=new World(7319),motion=matchMedia('(prefers-reduced-motion: reduce)');
// Select a bounded open patch once; actual world collisions remain authoritative in the study.
let anchor={x:0,y:0},best=-1;
for(let i=0;i<49;i++){const x=(i%7-3)*220,y=(Math.floor(i/7)-3)*220;if(world.blocked(x,y,16))continue;let score=0;for(let j=0;j<12;j++){const a=j*Math.PI/6;if(!world.blocked(x+Math.cos(a)*140,y+Math.sin(a)*140,20))score++;}if(score>best){best=score;anchor={x,y};}if(best===12)break;}
let study:SkillStudy,playing=false,frame=0,last=0,accumulator=0,events:Array<{time:number;type:string}>=[],disposed=false;
function list(query=''){root.querySelector('#skills')!.innerHTML=skills.filter(s=>`${s.name} ${s.domain} ${s.requirement}`.toLowerCase().includes(query.toLowerCase())).map(s=>`<button data-skill="${s.id}" aria-pressed="${s.id===id}"><span style="color:${s.color}">${skillIconSVG(s.id,25)}</span> ${e(s.name)}<small>${s.domain} · ${s.tier}</small></button>`).join('');}
function options(){field('weapon').innerHTML=studyWeapons(id).map(w=>`<option value="${w.id}">${e(w.name)}</option>`).join('');field('specialization').innerHTML='<option value="">Base skill</option>'+SKILL_SPECIALIZATIONS.filter(s=>s.skill===id).map(s=>`<option value="${s.id}">${e(s.name)}</option>`).join('');}
options();field('rank').value=String(boundedNumber(q.get('rank'),1,1,7));field('facing').value=String(boundedNumber(q.get('facing'),0,0,7));
for(const key of ['weapon','specialization','targets','enemy'])if([...field(key).options].some(o=>o.value===q.get(key)))field(key).value=q.get(key)!;
function configuration():SkillStudyOptions{return {skill:id,weapon:field('weapon').value,rank:Number(field('rank').value),specialization:field('specialization').value,facing:Number(field('facing').value)*Math.PI/4,targets:field('targets').value as SkillStudyOptions['targets'],enemy:field('enemy').value as EnemyKind,...anchor};}
function reset(){playing=false;accumulator=0;events=[];study=new SkillStudy(world,configuration());renderer.reset();renderer.resize(850,560);renderer.cameraX=anchor.x;renderer.cameraY=anchor.y;const s=SKILL_DEFINITIONS[id];
 root.querySelector('#skill-title')!.innerHTML=`<h2 style="color:${s.color}">${skillIconSVG(id,32)} ${e(s.name)}</h2><p>${e(s.description)}</p>`;
 root.querySelector('#costs')!.textContent=`${skillRequirementLabel(s.requirement)} · ${study.resolved.mana} mana · ${study.resolved.cooldown}s cooldown · ${study.resolved.damageMultiplier.toFixed(2)}× potency · Rank ${field('rank').value}`;
 root.querySelector('#recipe')!.textContent=JSON.stringify(study.resolved,null,2);root.querySelector('#events')!.textContent='';
 const params=new URLSearchParams({skill:id,...Object.fromEntries(new FormData(form) as Iterable<[string,string]>)});history.replaceState(null,'',`?${params}`);reportRoute();draw(0);buttons();}
function buttons(){root.querySelector<HTMLButtonElement>('#pause')!.disabled=!playing&&study.elapsed===0;root.querySelector('#pause')!.textContent=playing?'Pause':'Resume';}
function draw(dt:number){renderer.cameraX=anchor.x;renderer.cameraY=anchor.y;renderer.render(study.simulation,world,dt,{phase:'playing',reducedMotion:motion.matches,fps:60,debug:false});fx.render(renderer.canvas,study.elapsed);root.querySelector<HTMLProgressElement>('#timeline')!.value=study.elapsed;
 root.querySelector('.tool-status')!.textContent=`${study.elapsed.toFixed(2)} / 12.00s · ${study.didCast?'Skill activated':'Ready to cast'} · ${study.simulation.enemies.length} training targets · ${Math.round(study.damage)} damage · ${study.simulation.projectiles.length} projectiles · ${study.simulation.groundEffects.length} ground effects`;}
function step(){const emitted=study.step();renderer.handleEvents(emitted,motion.matches);events.push(...emitted.map(ev=>({time:Number(study.elapsed.toFixed(3)),type:ev.type})));events.splice(0,Math.max(0,events.length-100));if(emitted.length)root.querySelector('#events')!.textContent=events.map(ev=>`${ev.time.toFixed(3)}s  ${ev.type}`).join('\n');}
function tick(now:number){frame=0;if(disposed)return;const dt=last?Math.min(.05,(now-last)/1000):0;last=now;
 if(playing&&!document.hidden){accumulator+=dt*Number(root.querySelector<HTMLSelectElement>('#speed')!.value);let steps=0;while(accumulator>=1/120&&steps<24){step();accumulator-=1/120;steps++;}if(steps)draw(steps/120);
  if(study.elapsed>=12){if(root.querySelector<HTMLInputElement>('#loop')!.checked){reset();playing=true;}else playing=false;buttons();}}
 if(playing&&!document.hidden)frame=requestAnimationFrame(tick);}
function run(){if(!frame){last=0;frame=requestAnimationFrame(tick);}buttons();}
root.querySelector('#play')!.addEventListener('click',()=>{reset();playing=true;run();});root.querySelector('#pause')!.addEventListener('click',()=>{if(study.elapsed>=12)reset();playing=!playing;run();});root.querySelector('#reset')!.addEventListener('click',reset);root.querySelector('#step')!.addEventListener('click',()=>{playing=false;step();draw(1/120);buttons();});
form.addEventListener('submit',ev=>ev.preventDefault());form.addEventListener('change',reset);root.querySelector('#skills')!.addEventListener('click',ev=>{const b=(ev.target as Element).closest<HTMLElement>('[data-skill]');if(b){id=b.dataset.skill as SkillId;options();list(root.querySelector<HTMLInputElement>('#search')!.value);reset();}});root.querySelector<HTMLInputElement>('#search')!.addEventListener('input',ev=>list((ev.target as HTMLInputElement).value));
root.querySelector('#export')!.addEventListener('click',()=>downloadJSON(`evergrow-skill-${id}.json`,{options:study.options,resolved:study.resolved,elapsed:study.elapsed,events,damage:study.damage}));root.querySelector('#png')!.addEventListener('click',()=>{draw(0);const a=document.createElement('a');a.download=`skill-${id}-${study.elapsed.toFixed(2)}.png`;a.href=canvas.toDataURL('image/png');a.click();});
function visibility(){if(document.hidden){cancelAnimationFrame(frame);frame=0;last=0;accumulator=0;}else if(playing)run();}
document.addEventListener('visibilitychange',visibility);
function dispose(){document.removeEventListener('visibilitychange',visibility);disposed=true;cancelAnimationFrame(frame);renderer.reset();fx.dispose();world.dispose();}window.addEventListener('pagehide',dispose,{once:true});if(import.meta.hot)import.meta.hot.dispose(dispose);
list();reset();
